# Generated by Django 2.2.4 on 2020-09-25 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='who_liked',
            field=models.ManyToManyField(related_name='Who_liked_info', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='complaint_text',
            field=models.CharField(max_length=2000, verbose_name='Текст жалобы'),
        ),
    ]
