# Generated by Django 2.2.4 on 2020-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200925_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='complaint_text',
            field=models.TextField(max_length=2000, verbose_name='Текст жалобы'),
        ),
    ]
